LRU_Cache.java
CodeNerve/Let-Us-Java pull request #98
Opened 2021-10-04 04:56 UTC by Sakshamgupta90

Please review this PR

2021-10-04 08:14 UTC, Pradyuman7 commented
@Sakshamgupta90 please make sure the build passes for your PR, you can check the log to get more details regarding the failure, but here's a small part from it:
```
LeetCodeSolutions: Compilation failure
Error:  /home/runner/work/Let-Us-Java/Let-Us-Java/LeetCodeSolutions/src/main/java/LRU_Cache.java:[5,1] class, interface, or enum expected
```

2021-10-04 18:18 UTC, Sakshamgupta90 commented
@Pradyuman7 Sorry I didnt understand what's the problem can you please clarify!

2021-10-05 06:15 UTC, Pradyuman7 requested changes

2021-10-05 06:15 UTC, Pradyuman7 commented on LeetCodeSolutions/src/main/java/LRU_Cache.java
> +***** problem statement *****
This should not be here like this (add it as a comment or remove this)

2021-10-05 06:15 UTC, Pradyuman7 commented on LeetCodeSolutions/src/main/java/LRU_Cache.java
> +***** Solution *****
Same for this

2021-10-05 06:15 UTC, Pradyuman7 commented on LeetCodeSolutions/src/main/java/LRU_Cache.java
> + public class LRUCache {
File name and public class name should be the same

2021-10-05 06:47 UTC, Sakshamgupta90 commented
@Pradyuman7 now is this fine?

2021-10-05 08:53 UTC, Pradyuman7 approved these changes

2021-10-05 08:53 UTC, merged

2021-10-05 10:38 UTC, Sakshamgupta90 commented
@Pradyuman7 can you please add Hacktoberfest accepted tag in this.